"""
The knowledge-base text a judge is allowed to grade against.

This module is the reason the judge means anything. An LLM asked "is this a
correct answer about an Etnyre chip spreader?" grades against its own training
data, which contains no Etnyre manual - so it rewards a fluent answer and
punishes a correct one that happens to be terse. Asked instead "is every claim
in this answer supported by THIS text?", it is doing a job it is genuinely good
at, and the KB becomes the arbiter rather than the model.

What is handed over is the SECTION the question came from, not the whole file.
Both bounds matter:

  * Too little and a correct answer that draws on the section's preamble - the
    safety warning, the tool list - reads as unsupported.
  * Too much and grounding stops discriminating. Given a whole KB, an answer
    describing the RC-36 gate procedure to an RC-28 caller is "supported by the
    manual", because some section somewhere supports it. That is exactly the
    cross-family defect assertions.failOnWrongControllerFamily exists to catch,
    and a whole-file context hides it.

scenarios.json already carries what is needed to find the section: `section`
(its heading) and `sourceLine` (where the question sits in the file). Those are
generated by tools/build_resources.py from the KB itself, so a section renamed
in the manual is renamed here on the next `make resources` rather than drifting.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from functools import lru_cache
from typing import Any

from . import testbed

# `## Section 8 — Troubleshooting — Machine Systems`, and the general guide's
# `## Problem 12 — ...`.
SECTION_HEADING = re.compile(r"^##\s+(?P<title>\S.*?)\s*$")

# `### Q: The machine won't start / starter doesn't crank` - one entry inside a
# section. These are what scenarios are generated from, and a section can hold
# thirty of them, so the entry is the unit worth grounding on.
ENTRY_HEADING = re.compile(r"^###\s+(?P<title>\S.*?)\s*$")

# A warning the answer is expected to carry with it. The KBs write these as
# bold run-in labels rather than as admonition blocks.
WARNING_MARKER = re.compile(
    r"\b(warning|caution|danger|never|do not|must not|lockout|lock out|"
    r"before servicing|shut off the machine)\b",
    re.IGNORECASE,
)


@dataclass(frozen=True)
class KbSection:
    """One section of one knowledge base, as handed to the judge."""

    kb_id: str
    kb_file: str
    machine: str
    controller: str | None
    heading: str
    start_line: int
    end_line: int
    text: str
    truncated: bool


    def citation(self) -> str:
        """Where to look when a score is disputed. Every failure message
        carries this, because the first question anyone asks about a judge's
        verdict is 'says who?'."""
        return f"{self.kb_file}:{self.start_line}-{self.end_line} ({self.heading})"


@lru_cache(maxsize=16)
def _lines(kb_id: str) -> tuple[str, ...]:
    kb = testbed.kb_by_id(kb_id)
    path = testbed.kb_path(kb)
    if not path.exists():
        raise FileNotFoundError(
            f"{path} is missing. knowledgeBases[].file in "
            f"{testbed.config_path()} points at it - rename it there, not here."
        )
    return tuple(path.read_text(encoding="utf-8").splitlines())


def _bounds(
    lines: tuple[str, ...], source_line: int, pattern: re.Pattern[str]
) -> tuple[int, int]:
    """
    The block delimited by `pattern` that contains `source_line`, as 1-based
    inclusive bounds. Falls back to the whole file when no heading matches -
    a shape none of the current five KBs use, but cheaper to tolerate than to
    assert against.
    """
    index = max(0, min(source_line - 1, len(lines) - 1))

    start = 0
    for i in range(index, -1, -1):
        if pattern.match(lines[i]):
            start = i
            break

    end = len(lines) - 1
    for i in range(index + 1, len(lines)):
        if pattern.match(lines[i]):
            end = i - 1
            break

    return start + 1, end + 1


def _grounding_text(lines: tuple[str, ...], source_line: int) -> tuple[str, int, int, int]:
    """
    Preamble + entry: the smallest slice that can fairly judge one answer.

    Returns (text, section_start, section_end, offset_of_source_line).

    A troubleshooting section in these KBs runs to several hundred lines and
    holds thirty independent `### Q:` entries. Handing all of it over is the
    over-wide failure this module's docstring warns about - and it is not
    hypothetical: Section 8 of vhrs28.md is 474 lines, so the entry the caller
    actually asked about is under two percent of what the judge would read.

    But the entry alone is too narrow. These sections open with the warning and
    the tool list that govern every entry beneath them - "shut off the machine
    completely before servicing" is written once, at the top, not repeated in
    each of the thirty. Grading an answer that carries that warning against a
    slice that does not contain it marks the agent down for being careful.

    So: the section's preamble (heading down to its first `###`) plus the one
    entry the question came from. If the section has no entries, the section is
    the unit.
    """
    sec_start, sec_end = _bounds(lines, source_line, SECTION_HEADING)

    first_entry = None
    for i in range(sec_start - 1, sec_end):
        if ENTRY_HEADING.match(lines[i]):
            first_entry = i + 1
            break

    if first_entry is None:
        text = "\n".join(lines[sec_start - 1 : sec_end]).strip("\n")
        offset = len("\n".join(lines[sec_start - 1 : max(sec_start - 1, source_line - 1)]))
        return text, sec_start, sec_end, offset

    entry_start, entry_end = _bounds(lines, source_line, ENTRY_HEADING)
    entry_start = max(entry_start, first_entry)
    entry_end = min(entry_end, sec_end)

    preamble = "\n".join(lines[sec_start - 1 : first_entry - 1]).strip("\n")
    entry = "\n".join(lines[entry_start - 1 : entry_end]).strip("\n")

    if preamble and entry_start > first_entry:
        text = f"{preamble}\n\n{entry}"
        offset = len(preamble) + 2
    else:
        text = entry or preamble
        offset = 0

    return text, sec_start, sec_end, offset


def _clamp(text: str, source_offset: int, limit: int) -> tuple[str, bool]:
    """
    Trim an over-long section to `limit` characters, keeping the question's own
    line in the middle rather than keeping the first N characters.

    A section that opens with a twenty-row parts table and answers the question
    at the bottom is common in these KBs, and a head-truncated slice would drop
    the answer and leave the table - producing a confident "unsupported" verdict
    on a correct reply. The cut is marked so a reader of the report can tell a
    real gap from a windowing artefact.
    """
    if len(text) <= limit:
        return text, False

    half = limit // 2
    start = max(0, source_offset - half)
    end = min(len(text), start + limit)
    start = max(0, end - limit)

    body = text[start:end]
    prefix = "[... earlier in this section omitted ...]\n" if start > 0 else ""
    suffix = "\n[... later in this section omitted ...]" if end < len(text) else ""
    return prefix + body + suffix, True


def section_for(scenario: dict[str, Any], limit: int | None = None) -> KbSection:
    """
    The KB section a scenario's question came from.

    `limit` defaults to judge.contextSectionChars. Pass an explicit value only
    in tests that are measuring the windowing itself.
    """
    kb_id = scenario["kbId"]
    kb = testbed.kb_by_id(kb_id)
    lines = _lines(kb_id)

    source_line = int(scenario.get("sourceLine") or 1)
    text, start, end, offset = _grounding_text(lines, source_line)

    if limit is None:
        limit = int(testbed.judge_config()["contextSectionChars"])
    text, truncated = _clamp(text, offset, limit)

    heading = scenario.get("section") or ""
    if not heading:
        match = SECTION_HEADING.match(lines[start - 1]) if start - 1 < len(lines) else None
        heading = match.group("title") if match else f"{kb['file']} lines {start}-{end}"

    return KbSection(
        kb_id=kb_id,
        kb_file=kb["file"],
        machine=kb["machine"],
        controller=kb.get("controller"),
        heading=heading,
        start_line=start,
        end_line=end,
        text=text,
        truncated=truncated,
    )


def other_controller_families(kb_id: str) -> list[str]:
    """
    The controller families this answer must NOT drift into.

    Used by the controllerFamily rubric. Handing the judge the list rather than
    the word "wrong" is what makes the verdict checkable: it can quote the
    RC-36 reference it found in an answer to an RC-28 caller.
    """
    this = testbed.kb_by_id(kb_id).get("controller")
    if not this:
        return []  # the general guide is family-neutral by design
    families = {
        kb.get("controller") for kb in testbed.knowledge_bases(serial_routed_only=True)
    }
    return sorted(f for f in families if f and f != this)
